[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.149", features = ["derive"] }
bincode = "1.3.3"

[dependencies.networking]
path = "../networking"

[dependencies.app]
path = "../app"

[lib]
name = "client"
path = "src/lib.rs"
