[package]
name = "reliable_udp"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
random = "0.13"
bincode = "1.3.3"
serde = { version = "1.0.149", features = ["derive"] }

[lib]
name = "reliable_udp"
path = "src/lib.rs"
