[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
random = "0.13"
serde = { version = "1.0.149", features = ["derive"] }
bincode = "1.3.3"
winit = { version = "0.27.5", features = ["serde"] }

[lib]
name = "app"
path = "src/lib.rs"
