[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium = "0.2.0"

[dependencies.networking]
path = "../networking"

[dependencies.app]
path = "../app"
features = ["server"]
